import sys,os
print("""
Basic Termux commands 
V 1.0
""")
os.system("pkg update -y")
print("Package manager updated successfully.")
os.system("pkg upgrade -y")
print("Packages upgraded successfully.")
os.system("pkg install python -y")
print("Python installed successfully.")
os.system("pkg install python2 -y")
print("Python 2 installed successfully.")
os.system("pkg install python2-dev -y")
print("Python 2 development libraries installed successfully.")
os.system("pkg install python3 -y")
print("Python 3 installed successfully.")
os.system("pkg install java -y")
print("Java installed successfully.")
os.system("pkg install fish -y")
print("Fish shell installed successfully.")
os.system("pkg install ruby -y")
print("Ruby installed successfully.")
os.system("pkg install help")
print("Help command installed successfully.")
os.system("pkg install git -y")
print("Git installed successfully.")
os.system("pkg install host -y")
print("Host command installed successfully.")
os.system("pkg install php -y")
print("PHP installed successfully.")
os.system("pkg install perl -y")
print("Perl installed successfully.")
os.system("pkg install nmap -y")
print("Nmap installed successfully.")
os.system("pkg install bash -y")
print("Bash shell installed successfully.")
os.system("pkg install clang -y")
print("Clang compiler installed successfully.")
os.system("pkg install nano -y")
print("Nano text editor installed successfully.")
os.system("pkg install w3m -y")
print("w3m web browser installed successfully.")
os.system("pkg install havij -y")
print("HaviJ tool installed successfully.")
os.system("pkg install hydra -y")
print("Hydra tool installed successfully.")
os.system("pkg install figlet -y")
print("Figlet tool installed successfully.")
os.system("pkg install cowsay -y")
print("Cowsay tool installed successfully.")
os.system("pkg install curl -y")
print("Curl tool installed successfully.")
os.system("pkg install tar -y")
print("Tar tool installed successfully.")
os.system("pkg install zip -y")
print("Zip tool installed successfully.")
os.system("pkg install unzip -y")
print("Unzip tool installed successfully.")
os.system("pkg install tor -y")
print("Tor installed successfully.")
os.system("pkg install google -y")
print("Google search installed successfully.")
os.system("pkg install sudo -y")
print("Sudo command installed successfully.")
os.system("pkg install wget -y")
print("Wget tool installed successfully.")
os.system("pkg install wireshark -y")
print("Wireshark network analyzer installed successfully.")
os.system("pkg install wgetrc -y")
print("Wget configuration file installed successfully.")
os.system("pkg install wcalc -y")
print("Wcalc calculator installed successfully.")
os.system("pkg install bmon -y")
print("Bmon bandwidth monitor installed successfully.")
os.system("pkg install vpn -y")
print("VPN tools installed successfully.")
os.system("pkg install unrar -y")
print("Unrar tool installed successfully.")
os.system("pkg install toilet -y")
print("Toilet tool installed successfully.")
os.system("pkg install proot -y")
print("Proot chroot tool installed successfully.")
os.system("pkg install net-tools -y")
print("Net-tools network utilities installed successfully.")
os.system("pkg install golang -y")
print("Golang compiler installed successfully.")
os.system("pkg install chroot -y")
print("Chroot tool installed successfully.")
os.system("termux-chroot -y")
print("Chroot environment created successfully.")
os.system("pkg install macchanger -y")
print("Macchanger successfully.")
os.system("pkg install openssl -y")
print("successfully.")
os.system("pkg install cmatrix -y")
print("successfully.")
os.system("pkg install openssh -y")
print("successfully.")
os.system("pkg install wireshark -y")
print("successfully.")
os.system("termux-setup-storage -y")
print("successfully.")
os.system("pkg install macchanger -y")
print("successfully.")
os.system("apt update && apt upgrade -y")
print("successfully.")
print("الان تستطيع استخدم ترمكس")